---

- name: IOSXE Version Playbook no Splunk Inventory
  hosts: all
  vars_files: 
    - ./images.yml
  gather_facts: false
  connection: network_cli

  # Ansible: 2.9.26
  # pip install pyats genie
  # ansible-galaxy install -r requirements.yml (https://github.com/CiscoDevNet/ansible-pyats)

  # NOTE: You may need to increase copy image timeouts, please test manually before running this playbook 

  ## These variable can also be defined in a file or group or host vars.
  vars_prompt:
    - name: http_server
      prompt: "Enter IP address of http server"
      private : no
    - name: ansible_user
      prompt: "Enter username"
      private: no
    - name: ansible_password
      prompt: "Enter password" 
      private: yes

  vars:
    install_check_mode: "no"

  ## Make sure you have the following role installed.
  roles:
    - ansible-pyats
  ##Gather Facts to display
  tasks:
    - name: Gather facts for Devices
      tags: pre-check, check-version, install, upgrade
      ios_facts:
        gather_subset:
          - all
      register: device_info

    ##Check http server
    ##- name: Check http availability
    ##  ansible.builtin.uri:
    ##    url: "http://{{ http_server }}/http/"
    ##    method: GET
    ##    status_code: 200
    ##    retries: 5
    ##    delay: 5
    ##  register: http_check_result
    ##  failed_when: http_check_result.status != 200
    ##  tags: http_check
  
 ##Get platform type
    - name: Get show version
      tags: pre-check, check-version, post-check, install
      ios_command:
        commands: 
          - show version
      register: show_version

    - name: Set IOS Fact for platform
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform: "{{ show_version['stdout'][0] | pyats_parser('show version', 'ios') }}"
      when: ansible_net_iostype == 'IOS'

    - name: Set IOS XE Fact for platform 
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform: "{{ show_version['stdout'][0] | pyats_parser('show version', 'iosxe') }}"
      when: ansible_net_iostype == 'IOS-XE'

    ##set fact for platform type based on IOS or IOS-XE
    - name: Set IOS Fact for platform
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "{{ platform.version.platform | lower }}"
      when: ansible_net_iostype == 'IOS'

    - name: Set IOS XE Fact for platform
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "{{ platform.version.chassis | split('-') | first | lower }}"
      when: ansible_net_iostype == 'IOS-XE'

    - name: Fix WS string
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "{{ (platform.version.chassis | split('-'))[1] | lower }}"
      when: "'ws' in platform_type"

    - name: Set Fact for platform 9200 ios xe lite
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "c9200l"
      when: "'9200' in platform_type"


    - name: Set Fact for platform 9300, 9400, 9500, 9600
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "c9000"
      when: "'9300' in platform_type or '9400' in platform_type or 'c9500' in platform_type or '9600' in platform_type"
    
    - name: Set Fact for platform 3650 3860
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "cat3k"
      when: "'3650' in platform_type or '3850' in platform_type"

    - name: Set Fact for platform c8200, c8200l, c8300
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "c8000"
      when: "'8200' in platform_type or '8300' in platform_type"

    - name: Set Fact for platform isr4221
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "isr4200"
      when: "'4221' in platform_type"

    - name: Set Fact for platform isr4321, isr4331, isr4351
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "isr4300"
      when: "'4321' in platform_type or '4331' in platform_type or '4351' in platform_type"

    - name: Set Fact for platform isr4431, isr4451
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "isr4400"
      when: "'4431' in platform_type or '4451' in platform_type"

    - name: Set Fact for platform isr4461
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "c4400v2"
      when: "'4461' in platform_type"

    - name: Set Fact for platform asr1001x, asr1001hx, 1002hx
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "asr1000"
      when: "'asr1001' in platform_type or 'asr1002hx' in platform_type" 
    
    - name: Set Fact for platform asr1002x
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "asr1002"
      when: "'asr1002x' in platform_type"
  
    - name: Set Fact for platform asr1004
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "asr1004"
      when: "'asr1004' in platform_type"
    
    - name: Set Fact for platform asr1006
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "asr1006"
      when: "'asr1006' in platform_type"
    
    - name: Set Fact for platform asr1006x
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "asr1006x"
      when: "'asr1006x' in platform_type"

    - name: Set Fact for platform asr1009x
      tags: pre-check, check-version, post-check, install
      set_fact:
        platform_type: "asr1009x"
      when: "'asr1009x'"
    

    ##set target_image
    - name: Set Fact for target image name using platform
      tags: pre-check, check-version, post-check, install
      set_fact:
        raw_target_image: "{{ platform_type }}_target_image"

    - name: Set Fact for target image using platform
      tags: pre-check, check-version, post-check, install
      set_fact:
        target_image: "{{ lookup('vars', raw_target_image) }}"

    ##set target_image_md5
    - name: Set Fact for target image name using platform
      tags: pre-check, check-version, post-check, install
      set_fact:
        target_image_md5_raw: "{{ platform_type }}_md5_hash"

    - name: Set Fact for target md5
      tags: pre-check, check-version, post-check, install
      set_fact:
        target_image_md5: "{{ lookup('vars', target_image_md5_raw) }}"

    ##set target_image_size
    - name: Set Fact for target image name using platform
      tags: pre-check, check-version, post-check, install
      set_fact:
        target_image_size_raw: "{{ platform_type }}_image_size_bytes"

    - name: Set Fact for target md5
      tags: pre-check, check-version, post-check, install
      set_fact:
        target_image_size: "{{ lookup('vars', target_image_size_raw) }}"

    ##set target_ver
    - name: Set Fact for target image code
      tags: pre-check, check-version, post-check, install
      set_fact:
        target_image_code_raw: "{{ platform_type }}_image_code"

    - name: Set Fact for target md5
      tags: pre-check, check-version, post-check, install
      set_fact:
        target_ver: "{{ lookup('vars', target_image_code_raw) }}"

    - name: Set Flash Directory Fact
      tags: pre-check, check-version, post-check, install
      set_fact:
        flash_dir: "{{ ansible_net_image | split(':') | first }}:"
      when: ansible_net_iostype == 'IOS-XE'

     ##print variables 
    - name: Basic Facts for "{{ inventory_hostname }}"
      vars:
        msg: |
          Device Model: {{ device_info.ansible_facts.model }}
          Device Platform: {{ platform_type }}
          Serial Number: {{ ansible_net_serialnum }}
          Current IOS Version: {{ ansible_net_version }}
          Current IOS Image: {{ ansible_net_image }}
          IOS Type: {{ platform_os }}
          Target Image: {{ target_image }}
          Target Image Code: {{ target_ver }}
          Target Image Hash: {{ target_image_md5 }}
          Target Image size: {{ target_image_size }}
          Free Diskspace (kb): {{ ansible_net_filesystems_info[flash_dir]['spacefree_kb'] }}
      debug:
        msg: "{{ msg.split('\n') }}"
      tags: pre-check, check-version, install