---

- name: Group Display and selection
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: target_hosts
      prompt: |
        Available groups:
        {% for g in groups.keys() | sort %}
        - {{ g }}
        {% endfor %}
        
        Enter host(s) or group(s) separated by commas (e.g., router,switch1,switch4)
      private: no
    
  tasks:
    - name: Store answers as facts for next play
      set_fact:
        target_hosts: "{{ target_hosts }}"
      run_once: true
      no_log: true

- name: Show configured bandwidth
  hosts: "{{ hostvars['localhost']['target_hosts'].split(',') }}"
  gather_facts: false

  vars_prompt:
    - name: ansible_user
      prompt: "Enter username"
      private: no
    - name: ansible_password
      prompt: "Enter password"
      private: yes

  tasks:
    - name: Get show version
      tags: pre-check, check-version, post-check, install
      ios_command:
        commands: 
          - show platform hardware throughput crypto
      register: throughput

    - name: Display crypto throughput
      ansible.builtin.debug:
        msg: |
          Device: {{ inventory_hostname }}
          {% if throughput.stdout[0] is defined %}
          {{ throughput.stdout[0] }}
          {% else %}
          No output received or command failed.
          {% endif %}

    

