---
required_radius_servers:
  - name: server1
    ip: 1.1.1.1
    auth_port: 1812
    acct_port: 1813

  - name: server2
    ip: 2.2.2.2
    auth_port: 1812
    acct_port: 1813

  - name: server3
    ip: 3.3.3.3
    auth_port: 1812
    acct_port: 1813

